/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.GraphicsConfiguration;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import model.signupModel;
import service.signupInterface;

/**
 *
 * @author 25078
 */
public class SignUpF extends javax.swing.JFrame {
//    private String db_url="jdbc:mysql://localhost:3306/explore_movie_site_db";
//    private String db_username="root";
//    private String db_passwd=":@12ERgu#Oli";

    public SignUpF(GraphicsConfiguration gc) {
        super(gc);
    }

    public SignUpF(String string, GraphicsConfiguration gc) {
        super(string, gc);
    }
    

    /**
     * Creates new form SignUpF
     */
    public SignUpF() {
        initComponents(); 
        addItemsToCombo();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ChbxAge = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtPassConfirmation = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        BTNlogin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ageCombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        userType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\25078\\Desktop\\AUCA\\SMSTR6\\JAVA\\ProjectPic\\81a02f99506f76bcec87a9172fbd2d09.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChbxAge.setBackground(new java.awt.Color(255, 102, 51));
        ChbxAge.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Last Name");
        ChbxAge.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, -1));
        ChbxAge.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 267, -1));

        jLabel4.setText("First Name");
        ChbxAge.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, -1, -1));
        ChbxAge.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 267, -1));

        txtPassConfirmation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassConfirmationActionPerformed(evt);
            }
        });
        ChbxAge.add(txtPassConfirmation, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 267, -1));

        jLabel6.setText("Age");
        ChbxAge.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, -1, -1));
        ChbxAge.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 267, -1));

        btnRegister.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        ChbxAge.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, -1, -1));

        jLabel7.setText("Already have an account?");
        ChbxAge.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, -1, -1));

        BTNlogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BTNlogin.setText("Login");
        BTNlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNloginActionPerformed(evt);
            }
        });
        ChbxAge.add(BTNlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 440, 104, -1));

        jLabel8.setText("Password");
        ChbxAge.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, -1, -1));
        ChbxAge.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 267, -1));

        jLabel9.setText("email");
        ChbxAge.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, -1, -1));

        ageCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9", "10", "11", "12","13"}));
        ageCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageComboActionPerformed(evt);
            }
        });
        ChbxAge.add(ageCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 267, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Register here");
        ChbxAge.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, -1, -1));

        jLabel10.setText("Confirm Password");
        ChbxAge.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, -1, -1));

        userType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        userType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTypeActionPerformed(evt);
            }
        });
        ChbxAge.add(userType, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, -1, -1));

        jLabel1.setText("Role");
        ChbxAge.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\25078\\Desktop\\AUCA\\SMSTR6\\JAVA\\ProjectPic\\Register.jpg")); // NOI18N
        ChbxAge.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 540));

        getContentPane().add(ChbxAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNloginActionPerformed
        // TODO add your handling code here:
        LoginFr login = new LoginFr();
        dispose();
        login.setVisible(true);
    }
    
    private void addItemsToCombo(){
        //JComboBox<String> userType = new JComboBox<>();
        userType.removeAllItems();
        userType.addItem(userTypes.Admin.toString());
        userType.addItem(userTypes.User.toString());
      
    }//GEN-LAST:event_BTNloginActionPerformed
    
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        int selectedItem = ageCombo.getSelectedIndex();
          char ch = '@';
        String password = txtPassword.getText().trim();
        String confirmation = txtPassConfirmation.getText().trim();
        String email = txtemail.getText().trim();
        String choice = (String) ageCombo.getSelectedItem();
        //String Actor = (String) roleCombo.getSelectedItem();
        int age = Integer.parseInt(choice);
        if (txtFirstName.getText().trim().isEmpty() || 
            txtLastName.getText().trim().isEmpty() || 
            txtemail.getText().trim().isEmpty() || 
            (ageCombo.getSelectedItem() == null || ageCombo.getSelectedItem().toString().trim().isEmpty()) || 
            //(roleCombo.getSelectedItem() == null || roleCombo.getSelectedItem().toString().trim().isEmpty()) ||
            txtPassword.getText().trim().isEmpty() || 
            txtPassConfirmation.getText().isEmpty()
            ){
    JOptionPane.showMessageDialog(this, "All fields should be filled");
    //userType.getSelectedItem()==null || userType.getSelectedItem().toString().trim().isEmpty()
}

        else if((password.length()>=8) && (password.length()<=10) && (email.contains(Character.toString(ch)) && (age>=12))){
            if(confirmation.equals(password)){
                //JOptionPane.showMessageDialog(this, "Successfully logged in");  
                try{
                      signupModel signup = new signupModel();
                      signup.setFirstName(txtFirstName.getText());
                      signup.setLastName(txtLastName.getText());
                      signup.setEmail(txtemail.getText());
                      signup.setAge(Integer.parseInt(ageCombo.getSelectedItem().toString()));
                      signup.setPassword(txtPassword.getText());
                      signup.setUserRole(userType.getSelectedItem().toString());
                      Registry registry = LocateRegistry.getRegistry("127.0.0.1",5000);
                      signupInterface signups = (signupInterface)registry.lookup("signup");
                      String feedback = signups.registerUser(signup);
                      JOptionPane.showMessageDialog(this, feedback);
                }catch(Exception ex){
                    ex.printStackTrace();
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "the passwords are not equal");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "The passwords or email or age does not follow the required format", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void ageComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageComboActionPerformed
        // TODO add your handling code here:
      /*JComboBox<String> comboBox = new JComboBox<String>();*/
      /*ageCombo.addItem("10");
      ageCombo.addItem("12");
      ageCombo.addItem("13");
      ageCombo.addItem("15");
      ageCombo.insertItemAt("Item 1", 1);
      String selectedItem = (String) comboBox.getSelectedItem();*/
      String selectedItem = (String) ageCombo.getSelectedItem();
    }//GEN-LAST:event_ageComboActionPerformed

    private void txtPassConfirmationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassConfirmationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassConfirmationActionPerformed

    private void userTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTypeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_userTypeActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        SignUpF rolSignUpF = new SignUpF();


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNlogin;
    private javax.swing.JPanel ChbxAge;
    private javax.swing.JComboBox<String> ageCombo;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPassConfirmation;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtemail;
    private javax.swing.JComboBox<String> userType;
    // End of variables declaration//GEN-END:variables
}
